let shopItemsData = [
    {
        id: "1",
        name: "Casual Shirt",
        price: 45,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-1.jpg",
    },
    {
        id: "2",
        name: "Office Shirt",
        price: 100,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-2.jpg",
    },
    {
        id: "3",
        name: "T Shirt",
        price: 25,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-3.jpg",
    },
    {
        id: "4",
        name: "Mens Suit",
        price: 300,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-4.jpg",
    }, {
        id: "5",
        name: "Mens Tie",
        price: 25,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-5.jpg",
    },
    {
        id: "6",
        name: "Casual shoes",
        price: 200,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-6.jpg",
    },
    {
        id: "7",
        name: "black suit",
        price: 450,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-7.jpg",
    },
    {
        id: "8",
        name: "polo shirt",
        price: 45,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-8.jpg",
    },
    {
        id: "9",
        name: "denim shirt",
        price: 85,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-9.jpg",
    },
    {
        id: "10",
        name: "denim pants",
        price: 120,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-10.jpg",
    },
    {
        id: "11",
        name: "basic cap",
        price: 35,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-11.jpg",
    },
    {
        id: "12",
        name: "leather boots",
        price: 350,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-12.jpg",
    },
];